wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: huggingface
    huggingface_version: 4.6.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.7
    start_time: 1647221310
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      3:
      - 16
      - 17
      4: 3.7.7
      5: 0.12.10
      6: 4.6.0
      8:
      - 5
dataset:
  desc: null
  value: wiki_lingua english
learning_rate:
  desc: null
  value: 5.0e-05
per_device_train_batch_size:
  desc: null
  value: 4
